### ISSUE TITLE
Support for Luminus Shell 

### ISSUE THREAD

**Issue by Giovannimbesi25** [fthx/window-list-in-panel#1]
I notice poor contrast and visibility when using luminus shell, maybe the text color of windows title should be black.
Also It would be awesome to use system accent color to highlight focused window.
Thanks for your work.

![Screenshot From 2024-12-15 09-18-06](https://github.com/user-attachments/assets/3abacb84-f859-4421-86ec-7b3f4fe54c7b)

**Comment by fthx** [comment]
Yep, was made for native black panel.
So sorry but I won't do anything here. I tried to use this GNOME extension put to panel but I switched back to homemade task bar (lighter code and correctly disconnected signals).

If you're ok with that, please give a try to https://extensions.gnome.org/extension/7615/task-up-lite/ .
That's my active project now. I can include some code to move Workspace Indicator to the left, if installed?

**Comment by Giovannimbesi25** [comment]
Thanks for the reply.
I've tried it, but the it doesn't allow to see windows from all workspaces.
I close the issue

**Comment by fthx** [comment]
Ok yes, please try Task Up ( non Lite !):
https://extensions.gnome.org/extension/6556/task-up/
that allows to handle all workspaces (cf. prefs).

If you want to see all the windows, I can make Task Up Lite to show all windows (+= prefs UI).
But that's not the primary goal: if I show all windows on all workspaces, what's the goal to have many workspaces?

**Comment by fthx** [comment]
https://github.com/fthx/task-up-lite/commit/2f2fa1c68b3c08b80169659280d580cf596a7e1e
